spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/fastfood_order_db_dev}
    username: ${DATABASE_USERNAME:fastfood_user}
    password: ${DATABASE_PASSWORD:fastfood_password}
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.fastfood.order: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

